package com.hm;

import ch.aplu.turtle.Options;
import ch.aplu.turtle.Turtle;

import java.awt.*;

public class BingDwenDwen {
    public static void main(String[] args) {
        Options.setPlaygroundSize(760, 660);
        Options.setBackgroundColor(Turtle.toColor("lightgray"));
        MyTurtle turtle = new MyTurtle();
        turtle.setTitle("公众号-法式小奶包）");
        turtle.speed(-1);
//# 左手
        turtle.penUp();
        turtle.moveTo(177, 112);
        turtle.setPenColor("lightgray");
        turtle.setPenWidth(3);
        turtle.setFillColor("white");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(80);
        turtle.arc(-45, 200);
        turtle.arc(-300, 23);
        turtle.fillOff();
//# 左手内
        turtle.penUp();
        turtle.moveTo(182, 95);
        turtle.setPenColor("black");
        turtle.setPenWidth(1);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.setHeading(95);
        turtle.penDown();
        turtle.arc(-37, 160);
        turtle.arc(-20, 50);
        turtle.arc(-200, 30);
        turtle.fillOff();
//# 轮廓
//# 头顶
        turtle.penUp();
        turtle.moveTo(-73, 230);
        turtle.setPenColor("lightgray");
        turtle.setPenWidth(3);
        turtle.setFillColor("white");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(20);
        turtle.arc(-250, 35);
//# 左耳
        turtle.setHeading(50);
        turtle.arc(-42, 180);
//# 左侧
        turtle.setHeading(-50);
        turtle.arc(-190, 30);
        turtle.arc(-320, 45);
//# 左腿
        turtle.arc(120, 30);
        turtle.arc(200, 12);
        turtle.arc(-18, 85);
        turtle.arc(-180, 23);
        turtle.arc(-20, 110);
        turtle.arc(15, 115);
        turtle.arc(100, 12);
//# 右腿
        turtle.arc(15, 120);
        turtle.arc(-15, 110);
        turtle.arc(-150, 30);
        turtle.arc(-15, 70);
        turtle.arc(-150, 10);
        turtle.arc(200, 35);
        turtle.arc(-150, 20);
//# 右手
        turtle.setHeading(-120);
        turtle.arc(50, 30);
        turtle.arc(-35, 200);
        turtle.arc(-300, 23);
//# 右侧
        turtle.setHeading(86);
        turtle.arc(-300, 26);
//# 右耳
        turtle.setHeading(122);
        turtle.arc(-53, 160);
        turtle.fillOff();
//# 右耳内
        turtle.penUp();
        turtle.moveTo(-130, 180);
        turtle.setPenColor("black");
        turtle.setPenWidth(1);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(120);
        turtle.arc(-28, 160);
        turtle.setHeading(210);
        turtle.arc(150, 20);
        turtle.fillOff();
//# 左耳内
        turtle.penUp();
        turtle.moveTo(90, 230);
        turtle.setHeading(40);
        turtle.fillToPoint();
        turtle.penDown();
        turtle.arc(-30, 170);
        turtle.setHeading(125);
        turtle.arc(150, 23);
        turtle.fillOff();
//# 右手内
        turtle.penUp();
        turtle.moveTo(-180, -55);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.setHeading(-120);
        turtle.penDown();
        turtle.arc(50, 30);
        turtle.arc(-27, 200);
        turtle.arc(-300, 20);
        turtle.setHeading(-90);
        turtle.arc(300, 14);
        turtle.fillOff();
//# 左腿内
        turtle.penUp();
        turtle.moveTo(108, -168);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(-115);
        turtle.arc(110, 15);
        turtle.arc(200, 10);
        turtle.arc(-18, 80);
        turtle.arc(-180, 13);
        turtle.arc(-20, 90);
        turtle.arc(15, 60);
        turtle.setHeading(42);
        turtle.arc(-200, 29);
        turtle.fillOff();
//# 右腿内
        turtle.penUp();
        turtle.moveTo(-38, -210);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(-155);
        turtle.arc(15, 100);
        turtle.arc(-10, 110);
        turtle.arc(-100, 30);
        turtle.arc(-15, 65);
        turtle.arc(-100, 10);
        turtle.arc(200, 15);
        turtle.setHeading(-14);
        turtle.arc(-200, 27);
        turtle.fillOff();
//# 右眼
//# 眼圈
        turtle.penUp();
        turtle.moveTo(-64, 120);
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(40);
        turtle.arc(-35, 152);
        turtle.arc(-100, 50);
        turtle.arc(-35, 130);
        turtle.arc(-100, 50);
        turtle.fillOff();
//# 眼珠
        turtle.penUp();
        turtle.moveTo(-47, 55);
        turtle.setFillColor("white");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(25, 360);
        turtle.fillOff();
        turtle.penUp();
        turtle.moveTo(-45, 62);
        turtle.setPenColor("darkslategray");
        turtle.setFillColor("darkslategray");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(19, 360);
        turtle.fillOff();
        turtle.penUp();
        turtle.moveTo(-45, 68);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(10, 360);
        turtle.fillOff();
        turtle.penUp();
        turtle.moveTo(-47, 86);
        turtle.setPenColor("white");
        turtle.setFillColor("white");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(5, 360);
        turtle.fillOff();
//# 左眼
//# 眼圈
        turtle.penUp();
        turtle.moveTo(51, 82);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(120);
        turtle.arc(-32, 152);
        turtle.arc(-100, 55);
        turtle.arc(-25, 120);
        turtle.arc(-120, 45);
        turtle.fillOff();
//# 眼珠
        turtle.penUp();
        turtle.moveTo(79, 60);
        turtle.setFillColor("white");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(24, 360);
        turtle.fillOff();
        turtle.penUp();
        turtle.moveTo(79, 64);
        turtle.setPenColor("darkslategray");
        turtle.setFillColor("darkslategray");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(19, 360);
        turtle.fillOff();
        turtle.penUp();
        turtle.moveTo(79, 70);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(10, 360);
        turtle.fillOff();
        turtle.penUp();
        turtle.moveTo(79, 88);
        turtle.setPenColor("white");
        turtle.setFillColor("white");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(5, 360);
        turtle.fillOff();
//# 鼻子
        turtle.penUp();
        turtle.moveTo(37, 80);
        turtle.setFillColor("black");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(0);
        turtle.arc(-8, 130);
        turtle.arc(-22, 100);
        turtle.arc(-8, 130);
        turtle.fillOff();
//# 嘴
        turtle.penUp();
        turtle.moveTo(58, 48);
        turtle.setHeading(-132);
        turtle.penDown();
        turtle.setFillColor(Color.BLACK);
        turtle.fillToPoint();
        turtle.arc(-45, 100);
        turtle.fillOff();
        turtle.setHeading(-36);
        turtle.setFillColor(Color.WHITE);
        turtle.fillToPoint();
        turtle.arc(60, 72);
        turtle.fillOff();
//# 彩虹圈
        turtle.penUp();
        turtle.moveTo(-135, 120);
        turtle.setPenWidth(5);
        turtle.setPenColor("cyan");
        turtle.penDown();
        turtle.setHeading(60);
        turtle.arc(-165, 150);
        turtle.arc(-130, 78);
        turtle.arc(-250, 30);
        turtle.arc(-138, 105);
        turtle.penUp();
        turtle.moveTo(-131, 116);
        turtle.setPenColor("slateblue");
        turtle.penDown();
        turtle.setHeading(60);
        turtle.arc(-160, 144);
        turtle.arc(-120, 78);
        turtle.arc(-242, 30);
        turtle.arc(-135, 105);
        turtle.penUp();
        turtle.moveTo(-127, 112);
        turtle.setPenColor("orangered");
        turtle.penDown();
        turtle.setHeading(60);
        turtle.arc(-155, 136);
        turtle.arc(-116, 86);
        turtle.arc(-220, 30);
        turtle.arc(-134, 103);
        turtle.penUp();
        turtle.moveTo(-123, 108);
        turtle.setPenColor("gold");
        turtle.penDown();
        turtle.setHeading(60);
        turtle.arc(-150, 136);
        turtle.arc(-104, 86);
        turtle.arc(-220, 30);
        turtle.arc(-126, 102);
        turtle.penUp();
        turtle.moveTo(-120, 104);
        turtle.setPenColor("greenyellow");
        turtle.penDown();
        turtle.setHeading(60);
        turtle.arc(-145, 136);
        turtle.arc(-90, 83);
        turtle.arc(-220, 30);
        turtle.arc(-120, 100);
        turtle.penUp();
//# 爱心
        turtle.penUp();
        turtle.moveTo(220, 115);
        turtle.setPenColor("brown");
        turtle.setPenWidth(1);
        turtle.setFillColor("brown");
        turtle.fillToPoint();
        turtle.penDown();
        turtle.setHeading(36);
        turtle.arc(-8, 180);
        turtle.arc(-60, 24);
        turtle.setHeading(110);
        turtle.arc(-60, 24);
        turtle.arc(-8, 180);
        turtle.fillOff();
//# 五环
        turtle.penUp();
        turtle.moveTo(-5, -170);
        turtle.penDown();
        turtle.setPenColor("blue");
        turtle.arc(6);
        turtle.penUp();
        turtle.moveTo(10, -170);
        turtle.penDown();
        turtle.setPenColor("black");
        turtle.arc(6);
        turtle.penUp();
        turtle.moveTo(25, -170);
        turtle.penDown();
        turtle.setPenColor("brown");
        turtle.arc(6);
        turtle.penUp();
        turtle.moveTo(2, -175);
        turtle.penDown();
        turtle.setPenColor("lightgoldenrod");
        turtle.arc(6);
        turtle.penUp();
        turtle.moveTo(16, -175);
        turtle.penDown();
        turtle.setPenColor("green");
        turtle.arc(6);
        turtle.penUp();
        turtle.setPenColor("black");
        turtle.moveTo(-25, -150);
        turtle.setFont("Arial", Font.BOLD + Font.ITALIC, 14);
        turtle.label("BEIJING 2022");
        turtle.hideTurtle();
        // turtle.done();
    }
}